name: Integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  ICM_BASE_URL: http://pwa-review.northeurope.cloudapp.azure.com:8081
  COMPOSE_PROJECT_NAME: intershop-pwa-e2e
  COMPOSE_FILE: e2e/docker-compose.yml

jobs:
  CancelPrevious:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Old Pipeline
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'"
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  E2E:
    needs: [CancelPrevious]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: ['b2c', 'b2b']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Compose
        run: |
          docker compose build \
            --build-arg activeThemes=${{ matrix.test }} \
            --build-arg user=$UID \
            --build-arg cypressVersion=$(node -p -e 'require("./e2e/package.json").dependencies.cypress')

      - name: Start PWA
        run: docker compose up -d pwa

      - name: Universal
        run: docker compose run universal

      - name: Cypress
        run: |
          docker compose run \
            --user $UID \
            -w /e2e \
            -v $PWD/e2e/cypress:/e2e/cypress \
            cypress '**/*${{ matrix.test }}*.e2e-spec.ts'

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: e2e/cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: videos
          path: e2e/cypress/videos
